from typing import Optional
"""
Emotion-Triggered Adaptive Intervention Endpoint
POST /api/v1/emotion/intervention

Receives the live detected emotion and attention score from the Focus Monitor,
runs the 4-stage adaptive pipeline, and returns a contextual intervention
message generated by the Content Personalization Model.
"""

from fastapi import APIRouter
from pydantic import BaseModel, Field
from app.services.predict_readiness import predict_readiness, get_time_of_day
from app.services.content_personalization_service import ContentPersonalizationService

router = APIRouter(prefix="/api/v1/emotion", tags=["emotion-intervention"])

content_service = ContentPersonalizationService()

# Emotions that require immediate adaptive intervention
INTERVENTION_EMOTIONS = {"frustrated", "bored", "confused"}


class EmotionInterventionRequest(BaseModel):
    emotion: str = Field(..., description="Detected emotion: Focused, Neutral, Frustrated, Bored, Confused")
    attention_score: float = Field(50.0, ge=0.0, le=100.0, description="Real-time attention score 0-100")
    duration_seconds: int = Field(0, ge=0, description="How long this emotion has been sustained (seconds)")
    time_of_day: Optional[str] = Field(None, description="Morning, Afternoon, Evening, Night (auto-detected if None)")


@router.post("/intervention")
async def get_emotion_intervention(req: EmotionInterventionRequest):
    """
    Core emotion-aware adaptive notification endpoint.
    
    Pipeline:
    1. Readiness Model (emotion + time_of_day) → readiness_level (HIGH/MEDIUM/LOW)
    2. Content Personalization Model (emotion + readiness + focus_score) → intervention message
    3. Returns contextual notification with action, message, and route suggestion.
    
    Only intervenes when emotion is Frustrated, Bored, or Confused and the state
    has been sustained long enough (or attention drops below threshold).
    """
    emotion_lower = req.emotion.strip().lower()
    time_of_day = req.time_of_day or get_time_of_day()

    # Stage 1: Predict readiness via the trained Random Forest readiness model
    try:
        readiness_level = predict_readiness(req.emotion, time_of_day)
    except Exception:
        # Graceful fallback: infer readiness from emotion if model unavailable
        readiness_level = {
            "frustrated": "LOW",
            "bored": "LOW",
            "confused": "MEDIUM",
            "neutral": "MEDIUM",
            "focused": "HIGH",
        }.get(emotion_lower, "MEDIUM")

    # Stage 2: Content Personalization Model generates intervention
    intervention = content_service.generate_adaptive_intervention(
        emotion=req.emotion,
        readiness_level=readiness_level,
        focus_score=req.attention_score,
        time_of_day=time_of_day,
        duration_seconds=req.duration_seconds,
    )

    return {
        "emotion": req.emotion,
        "attention_score": req.attention_score,
        "time_of_day": time_of_day,
        "readiness_level": readiness_level,
        "intervention": intervention,
        "pipeline_source": "readiness_model + content_personalization_model",
    }
